### ISSUE TITLE
Provide nicer error message when service user does not exist

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#1]
When you try to deploy to the fcio infrastructure and the service user does not yet exist, you get something like...

```
jugmac00@jugmac00-XPS-13-9370:~/Projects/iq-reader.batou$ ./batou deploy production
Installing hg+https://bitbucket.org/flyingcircus/batou_ext@ad30396#egg=batou_ext
batou/1.11.0 (CPython 2.7.15-final0, Linux 4.15.0-1050-oem x86_64)
====================================================== Preparing =======================================================
main: Loading environment `production`...
main: Verifying repository ...
main: Loading secrets ...
================================================ Configuring first host ================================================
apisweb01: Connecting via ssh (1/1)
sudo: unknown user: s-iqreader
sudo: unable to initialize policy plugin
ERROR: Unexpected exception
      Traceback (most recent call last):
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/batou/deploy.py", line 141, in main
          deployment.configure()
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/batou/deploy.py", line 65, in configure
          self.connections.next().join()
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/batou/deploy.py", line 19, in run
          self.host.connect()
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/batou/host.py", line 181, in connect
          self.channel = self.gateway.remote_exec(remote_core)
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/execnet/gateway.py", line 126, in remote_exec
          channel = self.newchannel()
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1002, in newchannel
          return self._channelfactory.new()
        File "/home/jugmac00/Projects/iq-reader.batou/.batou/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 779, in new
          raise IOError("connexion already closed: %s" % (self.gateway,))
      IOError: connexion already closed: <Gateway id='gw1' not-receiving, thread model, 0 active channels>
      
================================================== DEPLOYMENT FAILED ===================================================
```

Instead, I'd like to see a similar excellent exception message like for errors in the File component:
```
                raise ValueError(
                    "Missing implicit template file {}. Or did you want "
                    "to create an empty file? Then use File('{}', content='')."
                    .format(guess_source, self._unmapped_path))
```

That means - what possible went wrong, and some suggestions what you could do to fix the problem yourself.

**Comment by ctheune** [comment]
Ok, so it's really hard to get that information in a structured way. However, the output already includes the relevant information - it's just really confusing due to the traceback.

I'm now rewriting the exception and hiding the traceback (unless you run with --debug):

```
➜  vagrant git:(master) ✗ ./batou deploy vagrant
Running unclean installation from requirements.txt
Ensuring unclean install ...
batou/2.1.dev0 (cpython 3.7.5-final0, Darwin 19.5.0 x86_64)
====================================================================================== Preparing =======================================================================================
main: Loading environment `vagrant`...
main: Verifying repository ...
You are using rsync. This is a non-verifying repository -- continuing on your own risk!
main: Loading secrets ...
==================================================================================== Connecting ... ====================================================================================
vagrant: Ensuring machines are up ...
default: Connecting via vagrant (1/1)
================================================================================ Configuring model ... =================================================================================
sudo: unknown user: myservice12
sudo: unable to initialize policy plugin
sudo: unknown user: myservice12
sudo: unable to initialize policy plugin
sudo: unknown user: myservice12
sudo: unable to initialize policy plugin
ERROR: Unexpected exception
      RuntimeError: Could not start batou on host `default`. The output above may contain more information.

================================================================================== DEPLOYMENT FAILED ===================================================================================
```
