### ISSUE TITLE
Python 3.5 support?

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#114]
Looks like `batou` still supports Python 3.5, but the test suite does not pass any longer...

```
❯ tox -e py35 -- -k test_appenv
py35 develop-inst-noop: /home/jugmac00/Projects/batou
py35 installed: apipkg==1.5,attrs==20.3.0,-e git+git@github.com:flyingcircusio/batou.git@493046ae8ac10bc3cefddfcc43d06e3c89d81569#egg=batou,certifi==2020.11.8,chardet==3.0.4,ConfigUpdater==1.0.1,coverage==5.3,execnet==1.7.1,idna==2.10,importlib-metadata==2.0.0,iniconfig==1.1.1,Jinja2==2.11.2,MarkupSafe==1.1.1,mock==3.0.5,packaging==20.4,pathlib2==2.3.5,pluggy==0.13.1,py==1.9.0,pyparsing==2.4.7,pytest==6.1.2,pytest-cov==2.10.1,pytest-cover==3.0.0,pytest-coverage==0.0,pytest-timeout==1.4.2,PyYAML==5.3.1,requests==2.25.0,six==1.15.0,toml==0.10.2,urllib3==1.26.2,zipp==1.2.0
py35 run-test-pre: PYTHONHASHSEED='324546741'
py35 run-test: commands[0] | pytest src/batou -k test_appenv
=================================================== test session starts ====================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: .tox/py35/.pytest_cache
rootdir: /home/jugmac00/Projects/batou, configfile: pytest.ini
plugins: cov-2.10.1, timeout-1.4.2
timeout: 45.0s
timeout method: signal
timeout func_only: False
collected 351 items / 350 deselected / 1 selected                                                                          

src/batou/lib/tests/test_appenv.py F                                                                                 [100%]

========================================================= FAILURES =========================================================
____________________________________________________ test_simple_appenv ____________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 332, in deploy
    self.verify, predicting=predict_only
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 398, in call_with_optional_args
    return func(**call_kw)
  File "/home/jugmac00/Projects/batou/src/batou/lib/appenv.py", line 12, in verify
    assert os.path.exists(self.parent.env_ready)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_appenv.py", line 12, in test_simple_appenv
    root.component.deploy()
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 320, in deploy
    sub_component.deploy(predict_only)
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 320, in deploy
    sub_component.deploy(predict_only)
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 340, in deploy
    self.update()
  File "/home/jugmac00/Projects/batou/src/batou/lib/appenv.py", line 20, in update
    "python{{component.python_version}} -m venv "
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 788, in cmd
    return batou.utils.cmd(cmd, silent, ignore_returncode, communicate, env)
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 359, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: ('python3 -m venv .appenv/86ef6495', 1, '', "Error: Command '['/tmp/pytest-of-jugmac00/pytest-1/test_simple_appenv0/work/mycomponent/.appenv/86ef6495/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1\n")
--------------------------------------------------- Captured stderr call ---------------------------------------------------
Exception ignored in: <_io.FileIO name='requirements.lock' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='requirements.lock' mode='r' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name='/home/jugmac00/Projects/batou/src/batou/lib/appenv.py' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/jugmac00/Projects/batou/src/batou/lib/appenv.py' mode='r' encoding='UTF-8'>
------------------------------- generated xml file: /home/jugmac00/Projects/batou/report.xml -------------------------------

---------- coverage: platform linux, python 3.5.10-final-0 -----------
Coverage HTML written to dir htmlcov

================================================= short test summary info ==================================================
FAILED src/batou/lib/tests/test_appenv.py::test_simple_appenv - batou.utils.CmdExecutionError: ('python3 -m venv .appenv/...
============================================ 1 failed, 350 deselected in 1.79s =============================================
Exception ignored in: <_io.FileIO name=9 mode='rb+' closefd=True>
ResourceWarning: unclosed file <_io.BufferedRandom name=9>
ERROR: InvocationError for command /home/jugmac00/Projects/batou/.tox/py35/bin/pytest src/batou -k test_appenv (exited with code 1)
_________________________________________________________ summary __________________________________________________________
ERROR:   py35: commands failed
```

**Comment by ctheune** [comment]
I think we need to consider dropping 3.5 support. I notice that I didn't include it in the move to Github Actions, but can't remember whether that was a real decision. Need to update docs, in any case.

**Comment by ctheune** [comment]
Ok, so Python 3.5 has been unsupported for about 8 months now and all of our platforms have at least Python 3.6 available. I'm happy to officially declare Python 3.5 unsupported.
