### ISSUE TITLE
Error during notify for successful deployment

### ISSUE THREAD

**Issue by sallner** [flyingcircusio/batou#124]
I tested a deployment with batou 2.2.2 and Python 3.8 and 3.9. I got a successful deployment but an error for the notification. 

```
Traceback (most recent call last):
  File ".batou/53add5ba/bin/batou", line 33, in <module>
    sys.exit(load_entry_point('batou==2.2.2', 'console_scripts', 'batou')())
  File "[...]/.batou/53add5ba/lib/python3.8/site-packages/batou/main.py", line 149, in main
    args.func(**func_args)
  File "[...]/.batou/53add5ba/lib/python3.8/site-packages/batou/deploy.py", line 268, in main
    notify("{} SUCCEEDED".format(ACTION), environment)
  File "[...]/.batou/53add5ba/lib/python3.8/site-packages/batou/utils.py", line 70, in notify_send
    subprocess.call(["notify-send", title, description])
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not Environment
```
Just by reading the code, it is not clear to me, how environment could be actually an `Environment` object instead of a string.

**Comment by sallner** [comment]
In batou 2.0 this behaviour was not present.

**Comment by ctheune** [comment]
Yeah, I refactored some stuff in 2.2 and there are some code paths that aren't detected by the coverage as we run them through shell-outs in the test. I'll fix this.
