### ISSUE TITLE
stable access to batou's venv needed

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#127]
After an unsuccessful deployment, the next deployment attempt always leads to ...

```
❯ ./batou deploy production
Removing expired path: .batou/5fc77caa ...
Creating venv ...
Traceback (most recent call last):
  File "/home/jugmac00/Projects/carm_ng_demo.batou/./batou", line 430, in <module>
    main()
  File "/home/jugmac00/Projects/carm_ng_demo.batou/./batou", line 426, in main
    meta_args.func(argv, meta_args)
  File "/home/jugmac00/Projects/carm_ng_demo.batou/./batou", line 256, in run_app
    env_dir = _prepare(meta_args)
  File "/home/jugmac00/Projects/carm_ng_demo.batou/./batou", line 230, in _prepare
    ensure_venv(env_dir)
  File "/home/jugmac00/Projects/carm_ng_demo.batou/./batou", line 72, in ensure_venv
    venv.create(target, with_pip=False)
  File "/usr/lib/python3.9/venv/__init__.py", line 412, in create
    builder.create(env_dir)
  File "/usr/lib/python3.9/venv/__init__.py", line 73, in create
    self.setup_python(context)
  File "/usr/lib/python3.9/venv/__init__.py", line 243, in setup_python
    copier(context.executable, path)
  File "/usr/lib/python3.9/venv/__init__.py", line 186, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jugmac00/Projects/carm_ng_demo.batou/.batou/5fc77caa/bin/python3.9'
```

I have to manually delete the `5fc77caa` folder, then batou is working again.

**Comment by jugmac00** [comment]
This error happens with batou 2.2.2 - as recommended by @zagy I went back to 2.0.2

**Comment by jugmac00** [comment]
Hm...  happens also on 2.0.2

```
bliss_deployment on  master [$!] via 🐍 v2.7.17 (2fafd634) 
❯ ./batou -h
Removing expired path: .batou/adcfd2bd ...
Creating venv ...
Ensuring pip ...
Installing batou ...
usage: batou [-h] [-d] {deploy,secrets} ...

batou v2.0.2: multi-(host|component|environment|version|platform) deployment

positional arguments:
  {deploy,secrets}
    deploy          Deploy an environment.
    secrets         Manage encrypted secret files. Relies on gpg being installed and configured correctly.

optional arguments:
  -h, --help        show this help message and exit
  -d, --debug       Enable debug mode. (default: False)

bliss_deployment on  master [$!] via 🐍 v3.9.1 (2fafd634) took 7s 
❯ ./batou deploy dev
Removing expired path: .batou/2fafd634 ...
Creating venv ...
Traceback (most recent call last):
  File "/home/jugmac00/Projects/bliss_deployment/./batou", line 430, in <module>
    main()
  File "/home/jugmac00/Projects/bliss_deployment/./batou", line 426, in main
    meta_args.func(argv, meta_args)
  File "/home/jugmac00/Projects/bliss_deployment/./batou", line 256, in run_app
    env_dir = _prepare(meta_args)
  File "/home/jugmac00/Projects/bliss_deployment/./batou", line 230, in _prepare
    ensure_venv(env_dir)
  File "/home/jugmac00/Projects/bliss_deployment/./batou", line 72, in ensure_venv
    venv.create(target, with_pip=False)
  File "/usr/lib/python3.9/venv/__init__.py", line 412, in create
    builder.create(env_dir)
  File "/usr/lib/python3.9/venv/__init__.py", line 73, in create
    self.setup_python(context)
  File "/usr/lib/python3.9/venv/__init__.py", line 243, in setup_python
    copier(context.executable, path)
  File "/usr/lib/python3.9/venv/__init__.py", line 186, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jugmac00/Projects/bliss_deployment/.batou/2fafd634/bin/python3.9'
```

**Comment by jugmac00** [comment]
Ok, I narrowed down how this happens.

```
/tmp/batou 
❯ curl -sL https://raw.githubusercontent.com/flyingcircusio/batou/master/bootstrap | sh
Updating lockfile
Creating venv ...
Ensuring pip ...
Installing packages ...
Creating venv ...
Ensuring pip ...
Installing batou ...
usage: batou [-h] [-d] {deploy,secrets} ...

batou v2.2.2: multi-(host|component|environment|version|platform) deployment

positional arguments:
  {deploy,secrets}
    deploy          Deploy an environment.
    secrets         Manage encrypted secret files. Relies on gpg being installed and configured correctly.

optional arguments:
  -h, --help        show this help message and exit
  -d, --debug       Enable debug mode. (default: False)

/tmp/batou via 🐍 v2.7.17 took 14s 
❯ ./batou --help
usage: batou [-h] [-d] {deploy,secrets} ...

batou v2.2.2: multi-(host|component|environment|version|platform) deployment

positional arguments:
  {deploy,secrets}
    deploy          Deploy an environment.
    secrets         Manage encrypted secret files. Relies on gpg being installed and configured correctly.

optional arguments:
  -h, --help        show this help message and exit
  -d, --debug       Enable debug mode. (default: False)

/tmp/batou via 🐍 v2.7.17 
❯ . .batou/d8334ceb/bin/activate

/tmp/batou via 🐍 v3.9.1 (d8334ceb) 
❯ ./batou
Removing expired path: .batou/d8334ceb ...
Creating venv ...
Traceback (most recent call last):
  File "/tmp/batou/./batou", line 430, in <module>
    main()
  File "/tmp/batou/./batou", line 426, in main
    meta_args.func(argv, meta_args)
  File "/tmp/batou/./batou", line 256, in run_app
    env_dir = _prepare(meta_args)
  File "/tmp/batou/./batou", line 230, in _prepare
    ensure_venv(env_dir)
  File "/tmp/batou/./batou", line 72, in ensure_venv
    venv.create(target, with_pip=False)
  File "/usr/lib/python3.9/venv/__init__.py", line 412, in create
    builder.create(env_dir)
  File "/usr/lib/python3.9/venv/__init__.py", line 73, in create
    self.setup_python(context)
  File "/usr/lib/python3.9/venv/__init__.py", line 243, in setup_python
    copier(context.executable, path)
  File "/usr/lib/python3.9/venv/__init__.py", line 186, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/batou/.batou/d8334ceb/bin/python3.9'
```

I usually activate the virtual environments I work with, as then my IDE has better autocompletion and does type checking.

**Comment by ctheune** [comment]
So what happens here: appenv assumes (due to the activated environment) that the outer python which was used to create this env has changed and wants to recreate it. It then deletes that old environment and tries to create a new one based on the deleted one. 

Short answer: don't do that. Those environments are not intended to be activated. Longer answer: appenv could provide you with a .batou/current link that you can use to have a stable reference to the environment without the need to activate it.

**Comment by ctheune** [comment]
I wonder whether appenv's `run` command would be sufficient here.

**Comment by ctheune** [comment]
So we actually do need a `.appenv/current` symlink (or "last"?) so that @jugmac00 can use it to point IDEs to the python environment for code completion, etc.

**Comment by elikoga** [comment]
This one is done by a change in appenv I think

**Comment by elikoga** [comment]
Added by https://github.com/flyingcircusio/appenv/pull/45

**Comment by elikoga** [comment]
`appenv_dir / "current" -> env_dir`
