### ISSUE TITLE
Notification shows repr instead of environment name

### ISSUE THREAD

**Issue by wosc** [flyingcircusio/batou#128]
![Screenshot 2021-01-12 at 12 44 52](https://user-images.githubusercontent.com/577891/104311579-ad77aa00-54d5-11eb-9b5b-06641dbcf121.png)

This used to say "Deployment succeeded: local" or similar. I've noticed this in 2.2.2, 2.0 was fine (I have no data from 2.1, sorry). I'm _guessing_ this might be an unwanted side effect of c547158, but that may well be way off the mark.

**Comment by wosc** [comment]
On (some?) Linux machines, this even actually breaks now:

```
Traceback (most recent call last):
  File ".batou/34090ccf/bin/batou", line 11, in <module>
    load_entry_point('batou==2.2.2', 'console_scripts', 'batou')()
  File "/home/hoshi/projects/friedbert-deployment/.batou/34090ccf/lib/python3.8/site-packages/batou/main.py", line 149, in main
    args.func(**func_args)
  File "/home/hoshi/projects/friedbert-deployment/.batou/34090ccf/lib/python3.8/site-packages/batou/deploy.py", line 268, in main
    notify("{} SUCCEEDED".format(ACTION), environment)
  File "/home/hoshi/projects/friedbert-deployment/.batou/34090ccf/lib/python3.8/site-packages/batou/utils.py", line 70, in notify_send
    subprocess.call(["notify-send", title, description])
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not Environment
```
