### ISSUE TITLE
Crash if gpg-public key cannot be found for encryption of secrets 

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#139]
Scenario: Having secrets for an environment having a key id inside memebers-list that is not inside the keyring. When saving/closing the secrets, batou is crashing

```
 % ./batou secrets edit vagrant        
gpg: 123456789_some_keyid: übersprungen: No public key
gpg: [stdin]: encryption failed: No public key
Traceback (most recent call last):
  File "/home/frlan/myproject.batou/.batou/920e41dd/bin/batou", line 33, in <module>
    sys.exit(load_entry_point('batou==2.2.3', 'console_scripts', 'batou')())
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/main.py", line 149, in main
    args.func(**func_args)
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/edit.py", line 114, in main
    editor.main()
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/edit.py", line 40, in main
    self.interact()
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/edit.py", line 46, in interact
    self.process_cmd(cmd)
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/edit.py", line 62, in process_cmd
    self.encrypt()
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/edit.py", line 79, in encrypt
    self.configfile.write()
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/encryption.py", line 172, in write
    file.write()
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/encryption.py", line 79, in write
    self._encrypt(self.cleartext)
  File "/home/frlan/myproject.batou/.batou/920e41dd/lib/python3.9/site-packages/batou/secrets/encryption.py", line 110, in _encrypt
    raise RuntimeError("GPG returned non-zero exit code.")
RuntimeError: GPG returned non-zero exit code.

```

**Comment by ctheune** [comment]
That was a bug introduced recently and got lost as debugging code. I'm fixing it and adding a test case now.
