### ISSUE TITLE
tox fails on my local dev machine

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#146]
on Ubuntu 18.04 

Is mercurial a (new) hard dependency to run tests? I remember running the tests successfully some time ago.

Also there are two connection tests, which failed.

GHA CI only runs when on push/pull request, not regularly, so I am not sure if the breakage is caused by a change of the environment, or is only local.

```
❯ tox -r -e py39
py39 recreate: /home/jugmac00/Projects/batou/.tox/py39
py39 develop-inst: /home/jugmac00/Projects/batou
py39 installed: apipkg==1.5,attrs==20.3.0,-e git+git@github.com:flyingcircusio/batou.git@4706c50df127ab9ebc9dcf3fde66733310ca807f#egg=batou,certifi==2020.12.5,chardet==4.0.0,ConfigUpdater==2.0,coverage==5.5,execnet==1.8.0,idna==2.10,iniconfig==1.1.1,Jinja2==2.11.3,MarkupSafe==1.1.1,mock==4.0.3,packaging==20.9,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pytest==6.2.2,pytest-cov==2.11.1,pytest-cover==3.0.0,pytest-coverage==0.0,pytest-timeout==1.4.2,PyYAML==5.4.1,requests==2.25.1,toml==0.10.2,urllib3==1.26.3
py39 run-test-pre: PYTHONHASHSEED='943860330'
py39 run-test: commands[0] | pytest src/batou
================================================================================= test session starts =================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py39/.pytest_cache
rootdir: /home/jugmac00/Projects/batou, configfile: pytest.ini
plugins: cov-2.11.1, timeout-1.4.2
timeout: 45.0s
timeout method: signal
timeout func_only: False
collected 359 items                                                                                                                                                                   

src/batou/lib/tests/test_appenv.py ..                                                                                                                                           [  0%]
src/batou/lib/tests/test_archive.py .......s.                                                                                                                                   [  3%]
src/batou/lib/tests/test_buildout.py ...                                                                                                                                        [  3%]
src/batou/lib/tests/test_cmmi.py ......                                                                                                                                         [  5%]
src/batou/lib/tests/test_cron.py .....                                                                                                                                          [  6%]
src/batou/lib/tests/test_debian.py ...                                                                                                                                          [  7%]
src/batou/lib/tests/test_download.py .....                                                                                                                                      [  9%]
src/batou/lib/tests/test_file.py ................................................................s..................                                                            [ 32%]
src/batou/lib/tests/test_git.py ..............                                                                                                                                  [ 36%]
src/batou/lib/tests/test_mercurial.py EEEEEEEEEEEE                                                                                                                              [ 39%]
src/batou/lib/tests/test_nagios.py .                                                                                                                                            [ 39%]
src/batou/lib/tests/test_python.py ..                                                                                                                                           [ 40%]
src/batou/lib/tests/test_service.py ...                                                                                                                                         [ 41%]
src/batou/lib/tests/test_supervisor.py .......                                                                                                                                  [ 43%]
src/batou/lib/tests/test_svn.py .                                                                                                                                               [ 43%]
src/batou/secrets/tests/test_editor.py ..                                                                                                                                       [ 44%]
src/batou/secrets/tests/test_secrets.py ............                                                                                                                            [ 47%]
src/batou/tests/test_component.py .............................................................                                                                                 [ 64%]
src/batou/tests/test_config.py ........                                                                                                                                         [ 66%]
src/batou/tests/test_dependencies.py ...........                                                                                                                                [ 69%]
src/batou/tests/test_deploy.py .                                                                                                                                                [ 69%]
src/batou/tests/test_endtoend.py .......                                                                                                                                        [ 71%]
src/batou/tests/test_environment.py ...........................                                                                                                                 [ 79%]
src/batou/tests/test_exceptions.py .                                                                                                                                            [ 79%]
src/batou/tests/test_host.py ...                                                                                                                                                [ 80%]
src/batou/tests/test_remote.py FF.                                                                                                                                              [ 81%]
src/batou/tests/test_remote_core.py .................                                                                                                                           [ 86%]
src/batou/tests/test_resources.py ..                                                                                                                                            [ 86%]
src/batou/tests/test_template.py .........                                                                                                                                      [ 89%]
src/batou/tests/test_utils.py .....................................                                                                                                             [ 99%]
src/batou/tests/test_vfs.py ..                                                                                                                                                  [100%]

======================================================================================= ERRORS ========================================================================================
_________________________________________________________________ ERROR at setup of test_runs_hg_to_clone_repository __________________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
__________________________________________________________ ERROR at setup of test_setting_branch_updates_on_incoming_changes __________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
__________________________________________________________________ ERROR at setup of test_branch_does_switch_branch ___________________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
_______________________________________________________ ERROR at setup of test_set_revision_does_not_pull_when_revision_matches _______________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
___________________________________________________ ERROR at setup of test_set_revision_does_not_change_when_long_revision_matches ____________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
_________________________________________________________ ERROR at setup of test_has_changes_counts_changes_to_tracked_files __________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
________________________________________________________ ERROR at setup of test_has_changes_counts_untracked_files_as_changes _________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
___________________________________________________________ ERROR at setup of test_clean_clone_updates_on_incoming_changes ____________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
_____________________________________________________________ ERROR at setup of test_changes_lost_on_update_with_incoming _____________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
____________________________________________________________ ERROR at setup of test_untracked_files_are_removed_on_update _____________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
___________________________________________________________ ERROR at setup of test_changes_lost_on_update_without_incoming ____________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
______________________________________________________ ERROR at setup of test_clean_clone_vcs_update_false_leaves_changes_intact ______________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_mercurial.py", line 10, in repos_path
    cmd("mkdir {dir}; cd {dir}; hg init;"
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
====================================================================================== FAILURES =======================================================================================
________________________________________________________________________ test_remote_deployment_initializable _________________________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/tests/test_remote.py", line 11, in test_remote_deployment_initializable
    cmd("hg init")
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
______________________________________________________________________ test_remote_bundle_breaks_on_missing_head ______________________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/tests/test_remote.py", line 21, in test_remote_bundle_breaks_on_missing_head
    cmd("hg init")
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 352, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
------------------------------------------------------------ generated xml file: /home/jugmac00/Projects/batou/report.xml -------------------------------------------------------------

----------- coverage: platform linux, python 3.9.2-final-0 -----------
Coverage HTML written to dir htmlcov

=============================================================================== short test summary info ===============================================================================
FAILED src/batou/tests/test_remote.py::test_remote_deployment_initializable - batou.utils.CmdExecutionError: The deployment encountered an error.
FAILED src/batou/tests/test_remote.py::test_remote_bundle_breaks_on_missing_head - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_runs_hg_to_clone_repository - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_setting_branch_updates_on_incoming_changes - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_branch_does_switch_branch - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_set_revision_does_not_pull_when_revision_matches - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_set_revision_does_not_change_when_long_revision_matches - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_has_changes_counts_changes_to_tracked_files - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_has_changes_counts_untracked_files_as_changes - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_clean_clone_updates_on_incoming_changes - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_changes_lost_on_update_with_incoming - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_untracked_files_are_removed_on_update - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_changes_lost_on_update_without_incoming - batou.utils.CmdExecutionError: The deployment encountered an error.
ERROR src/batou/lib/tests/test_mercurial.py::test_clean_clone_vcs_update_false_leaves_changes_intact - batou.utils.CmdExecutionError: The deployment encountered an error.
=========================================================== 2 failed, 343 passed, 2 skipped, 12 errors in 113.17s (0:01:53) ===========================================================
ERROR: InvocationError for command /home/jugmac00/Projects/batou/.tox/py39/bin/pytest src/batou (exited with code 1)
_______________________________________________________________________________________ summary _______________________________________________________________________________________
ERROR:   py39: commands failed
```

**Comment by ctheune** [comment]
Mercurial is a hard requirement, yes.

**Comment by jugmac00** [comment]
see #168 - I created a tox `testenv` to run tests without the one's for mercurial.
