### ISSUE TITLE
`Buildout` component does not work with `zc.buildout=3.0.0b1`

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#148]
`zc.buildout` version 2.13 possibly got the last maintenance release, and version 3 will be released soonish.

I tried it with my Zope app, got mislead to https://github.com/gocept/batou_scm/issues/11 but their `Buildout` inherits from the `Buildout` from here.

To reproduce ...

```
from batou.component import Component
from batou.lib.buildout import Buildout


class Demo(Component):
    def configure(self):
        self += Buildout(python="3.8", setuptools="54.1.1", version="3.0.0b1")
```

I get ...

```
❯ ./batou deploy dev
batou/2.2.4 (cpython 3.10.0-alpha6, Linux 5.4.0-66-generic x86_64)
====================================================== Preparing ======================================================
main: Loading environment `dev`...
main: Verifying repository ...
main: Loading secrets ...
=================================================== Connecting ... ====================================================
localhost: Connecting via local (1/1)
================================================ Configuring model ... ================================================
======================================== Waiting for remaining connections ... ========================================
====================================================== Deploying ======================================================
localhost: Scheduling component demo ...
localhost > Demo > Buildout > VirtualEnv('3.8') > Package('setuptools==54.1.1')
localhost > Demo > Buildout > VirtualEnv('3.8') > Package('zc.buildout==3.0.0b1')
localhost > Demo > Buildout
ERROR: bin/buildout -t 3 -c "buildout.cfg"
Return code: 1
STDOUT

STDERR
Traceback (most recent call last):
  File "bin/buildout", line 5, in <module>
    from zc.buildout.buildout import main
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 966, in <module>
    buildout_and_setuptools_dists = list(install(['zc.buildout'], None,
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 964, in install
    return installer.install(specs, working_set)
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 737, in install
    for dist in self._get_dist(req, ws):
  File "/home/jugmac00/Projects/batou_buildout3/work/demo/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 554, in _get_dist
    raise zc.buildout.UserError(
zc.buildout.UserError: We don't have a distribution for wheel
and can't install one in offline (no-install) mode.



========================================== DEPLOYMENT FAILED (during deploy) ==========================================
```

Works with `zc.buildout=2.13.4`.

**Comment by jugmac00** [comment]
When I patch `batou.lib.buildout.Buildout.configure` and add a line like `venv += Package("wheel", version="0.36.2")` the `batou` deployment is successful.

Pinning to a fixed version is probably not that good, not pinning is bad solution either... 

What's left? Make it configurable via the constructor?

Up to you.
