### ISSUE TITLE
batou always uses latest python3 version

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#153]
... which is not what I want, as I have Python 3.10.0-alpha6 installed to test my apps locally, but I certainly do not want to run batou with it, and batou currently does not support Python 3.10 anyway.

```
❯ ./batou deploy staging
Running unclean installation from requirements.txt
Creating venv ...
Ensuring pip ...
Ensuring unclean install ...
batou/2.2.3 (cpython 3.10.0-alpha6, Linux 5.4.0-67-generic x86_64)
```

**Comment by jugmac00** [comment]
a side effect from using a developer version of Python...

```
❯ ./batou deploy staging
Running unclean installation from requirements.txt
Ensuring unclean install ...
.batou/unclean/bin/python -m pip install -r requirements.txt --upgrade returned with exit code 1
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "/usr/lib/python3.10/io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)

Traceback (most recent call last):
  File "/home/jugmac00/Projects/customerupload.batou/./batou", line 40, in cmd
    return subprocess.check_output([c], **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['.batou/unclean/bin/python -m pip install -r requirements.txt --upgrade']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugmac00/Projects/customerupload.batou/./batou", line 430, in <module>
    main()
  File "/home/jugmac00/Projects/customerupload.batou/./batou", line 426, in main
    meta_args.func(argv, meta_args)
  File "/home/jugmac00/Projects/customerupload.batou/./batou", line 256, in run_app
    env_dir = _prepare(meta_args)
  File "/home/jugmac00/Projects/customerupload.batou/./batou", line 187, in _prepare
    cmd(
  File "/home/jugmac00/Projects/customerupload.batou/./batou", line 44, in cmd
    raise ValueError(e.output.decode("ascii"))
ValueError: Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "/usr/lib/python3.10/io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

batou re-uses an old env, but Python 3.10 has changed by a recent update.

workaround -> delete `.batou` folder

**Comment by ctheune** [comment]
Alright. I added this as a feature to appenv which means you can now specify a prioritised list of acceptable Python versions per project. 

https://github.com/flyingcircusio/appenv/commit/24ee15600578c8aec3138bc9870494f65e18a325 and also documented in the README there.

By default we still choose the newest Python if you don't specify anything. According to the 'adults rule' of Python I'm considering adding an in-development version of Python to your PATH to be a "power move" and you have to know what you are doing.
