### ISSUE TITLE
buildout 3 test fails due to buildout / pip 21.1 incompatibility

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#169]
```
Run bin/tox
py36 create: /home/runner/work/batou/batou/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/runner/work/batou/batou/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py38 create: /home/runner/work/batou/batou/.tox/py38
py38 develop-inst: /home/runner/work/batou/batou
py38 installed: apipkg==1.5,attrs==21.2.0,-e git+https://github.com/flyingcircusio/batou@c811fad72083579e945d0c0eddfbdc85393f304a#egg=batou,certifi==2020.12.5,chardet==4.0.0,ConfigUpdater==2.0,coverage==5.5,execnet==1.8.0,idna==2.10,iniconfig==1.1.1,Jinja2==3.0.1,MarkupSafe==2.0.1,mock==4.0.3,packaging==20.9,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pytest==6.2.4,pytest-cov==2.12.0,pytest-cover==3.0.0,pytest-coverage==0.0,pytest-timeout==1.4.2,PyYAML==5.4.1,requests==2.25.1,toml==0.10.2,urllib3==1.26.4
py38 run-test-pre: PYTHONHASHSEED='3322565937'
py38 run-test: commands[0] | pytest src/batou
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
rootdir: /home/runner/work/batou/batou, configfile: pytest.ini
plugins: timeout-1.4.2, cov-2.12.0
timeout: 45.0s
timeout method: signal
timeout func_only: False
collected 364 items

src/batou/lib/tests/test_appenv.py ..                                    [  0%]
src/batou/lib/tests/test_archive.py .......s.                            [  3%]
src/batou/lib/tests/test_buildout.py ...F                                [  4%]
src/batou/lib/tests/test_cmmi.py ......                                  [  5%]
src/batou/lib/tests/test_cron.py .....                                   [  7%]
src/batou/lib/tests/test_debian.py ...                                   [  7%]
src/batou/lib/tests/test_download.py .....                               [  9%]
src/batou/lib/tests/test_file.py ....................................... [ 20%]
.........................s..................                             [ 32%]
src/batou/lib/tests/test_git.py ..............                           [ 35%]
src/batou/lib/tests/test_mercurial.py ............                       [ 39%]
src/batou/lib/tests/test_nagios.py .                                     [ 39%]
src/batou/lib/tests/test_python.py ..                                    [ 40%]
src/batou/lib/tests/test_service.py ...                                  [ 40%]
src/batou/lib/tests/test_supervisor.py .......                           [ 42%]
src/batou/lib/tests/test_svn.py .                                        [ 43%]
src/batou/secrets/tests/test_editor.py ..                                [ 43%]
src/batou/secrets/tests/test_secrets.py ............                     [ 46%]
src/batou/tests/test_component.py ...................................... [ 57%]
.......................                                                  [ 63%]
src/batou/tests/test_config.py ........                                  [ 65%]
src/batou/tests/test_dependencies.py ...........                         [ 68%]
src/batou/tests/test_deploy.py .                                         [ 69%]
src/batou/tests/test_endtoend.py ........                                [ 71%]
src/batou/tests/test_environment.py ...........................          [ 78%]
src/batou/tests/test_exceptions.py .                                     [ 79%]
src/batou/tests/test_host.py ...                                         [ 79%]
src/batou/tests/test_remote.py ...                                       [ 80%]
src/batou/tests/test_remote_core.py .................                    [ 85%]
src/batou/tests/test_resources.py ..                                     [ 85%]
src/batou/tests/test_template.py .........                               [ 88%]
src/batou/tests/test_utils.py ........................................   [ 99%]
src/batou/tests/test_vfs.py ..                                           [100%]

=================================== FAILURES ===================================
_______________________ test_runs_buildout3_successfully _______________________
Traceback (most recent call last):
  File "/home/runner/work/batou/batou/src/batou/component.py", line 332, in deploy
    call_with_optional_args(
  File "/home/runner/work/batou/batou/src/batou/utils.py", line 424, in call_with_optional_args
    return func(**call_kw)
  File "/home/runner/work/batou/batou/src/batou/lib/buildout.py", line 72, in verify
    installed.assert_component_is_current([Presence("bin/buildout")] +
  File "/home/runner/work/batou/batou/src/batou/component.py", line 671, in assert_component_is_current
    raise batou.UpdateNeeded()
batou.UpdateNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/batou/batou/src/batou/lib/tests/test_buildout.py", line 71, in test_runs_buildout3_successfully
    root.component.deploy()
  File "/home/runner/work/batou/batou/src/batou/component.py", line 320, in deploy
    sub_component.deploy(predict_only)
  File "/home/runner/work/batou/batou/src/batou/component.py", line 339, in deploy
    self.update()
  File "/home/runner/work/batou/batou/src/batou/lib/buildout.py", line 80, in update
    self.cmd('bin/buildout -t {} -c "{}"'.format(
  File "/home/runner/work/batou/batou/src/batou/component.py", line 776, in cmd
    return batou.utils.cmd(cmd, silent, ignore_returncode, communicate,
  File "/home/runner/work/batou/batou/src/batou/utils.py", line 384, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
----------------------------- Captured stdout call -----------------------------
host > MyComponent > Buildout > File('work/mycomponent/buildout3.cfg') > Presence('buildout3.cfg')
host > MyComponent > Buildout > File('work/mycomponent/buildout3.cfg') > Content('buildout3.cfg')
  buildout3.cfg ---
  buildout3.cfg +++
  buildout3.cfg @@ -0,0 +1,14 @@
  buildout3.cfg +[buildout]
  buildout3.cfg +parts = app
  buildout3.cfg +versions = versions
  buildout3.cfg +allow-picked-versions = false
  buildout3.cfg +
  buildout3.cfg +[app]
  buildout3.cfg +recipe = zc.recipe.egg
  buildout3.cfg +eggs = zc.buildout
  buildout3.cfg +interpreter = py
  buildout3.cfg +
  buildout3.cfg +[versions]
  buildout3.cfg +setuptools = 54.1.1
  buildout3.cfg +zc.buildout = 3.0.0b1
  buildout3.cfg +zc.recipe.egg = 2.0.7
host > MyComponent > Buildout > VirtualEnv('3') > VirtualEnvPy
host > MyComponent > Buildout > VirtualEnv('3') > Package('setuptools==54.1.1')
host > MyComponent > Buildout > VirtualEnv('3') > Package('wheel==0.36.2')
host > MyComponent > Buildout > VirtualEnv('3') > Package('zc.buildout==3.0.0b1')
host > MyComponent > Buildout
ERROR: bin/buildout -t 3 -c "buildout3.cfg"
Return code: 1
STDOUT
Setting socket time out to 3 seconds.
Creating directory '/tmp/pytest-of-runner/pytest-0/test_runs_buildout3_successful0/work/mycomponent/eggs'.
Creating directory '/tmp/pytest-of-runner/pytest-0/test_runs_buildout3_successful0/work/mycomponent/parts'.
Creating directory '/tmp/pytest-of-runner/pytest-0/test_runs_buildout3_successful0/work/mycomponent/develop-eggs'.
Getting distribution for 'zc.recipe.egg==2.0.7'.
An error occurred when trying to install /tmp/tmp6fj07r2tget_dist/zc.recipe.egg-2.0.7.tar.gz. Look above this message for any errors that were output by pip install.

STDERR
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '_main' from 'pip.__main__' (/tmp/pytest-of-runner/pytest-0/test_runs_buildout3_successful0/work/mycomponent/lib/python3.8/site-packages/pip/__main__.py)


--------- generated xml file: /home/runner/work/batou/batou/report.xml ---------

---------- coverage: platform linux, python 3.8.10-final-0 -----------
Coverage HTML written to dir htmlcov

=========================== short test summary info ============================
FAILED src/batou/lib/tests/test_buildout.py::test_runs_buildout3_successfully
============= 1 failed, 361 passed, 2 skipped in 218.95s (0:03:38) =============
ERROR: InvocationError for command /home/runner/work/batou/batou/.tox/py38/bin/pytest src/batou (exited with code 1)
py39 create: /home/runner/work/batou/batou/.tox/py39
SKIPPED: InterpreterNotFound: python3.9
pre-commit create: /home/runner/work/batou/batou/.tox/pre-commit
SKIPPED: InterpreterNotFound: python3.9
___________________________________ summary ____________________________________
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
ERROR:   py38: commands failed
SKIPPED:  py39: InterpreterNotFound: python3.9
SKIPPED:  pre-commit: InterpreterNotFound: python3.9
Error: Process completed with exit code 1.
```

Sounds like `pip`s broken: https://stackoverflow.com/questions/49836676

**Comment by ctheune** [comment]
Does this happen on your machine? Because I can't replicate it on mine and it fails on Github ...

**Comment by jugmac00** [comment]
The output is from GitHub actions - but the test suite also fails for me on my local 18.04 Ubuntu.

Actually, I have four causes for local test failure:
- no mercurial installed (will be resolved by #146)
- the buildout test, which also fails on GHA
- test_endtoend (2 failures)
- test_remote (2 failures)

```
________________________________________________________ test_runs_buildout3_successfully ________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 332, in deploy
    call_with_optional_args(
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 424, in call_with_optional_args
    return func(**call_kw)
  File "/home/jugmac00/Projects/batou/src/batou/lib/buildout.py", line 72, in verify
    installed.assert_component_is_current([Presence("bin/buildout")] +
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 671, in assert_component_is_current
    raise batou.UpdateNeeded()
batou.UpdateNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/lib/tests/test_buildout.py", line 71, in test_runs_buildout3_successfully
    root.component.deploy()
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 320, in deploy
    sub_component.deploy(predict_only)
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 339, in deploy
    self.update()
  File "/home/jugmac00/Projects/batou/src/batou/lib/buildout.py", line 80, in update
    self.cmd('bin/buildout -t {} -c "{}"'.format(
  File "/home/jugmac00/Projects/batou/src/batou/component.py", line 776, in cmd
    return batou.utils.cmd(cmd, silent, ignore_returncode, communicate,
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 384, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
-------------------------------------------------------------- Captured stdout call --------------------------------------------------------------
host > MyComponent > Buildout > File('work/mycomponent/buildout3.cfg') > Presence('buildout3.cfg')
host > MyComponent > Buildout > File('work/mycomponent/buildout3.cfg') > Content('buildout3.cfg')
  buildout3.cfg ---
  buildout3.cfg +++
  buildout3.cfg @@ -0,0 +1,14 @@
  buildout3.cfg +[buildout]
  buildout3.cfg +parts = app
  buildout3.cfg +versions = versions
  buildout3.cfg +allow-picked-versions = false
  buildout3.cfg +
  buildout3.cfg +[app]
  buildout3.cfg +recipe = zc.recipe.egg
  buildout3.cfg +eggs = zc.buildout
  buildout3.cfg +interpreter = py
  buildout3.cfg +
  buildout3.cfg +[versions]
  buildout3.cfg +setuptools = 54.1.1
  buildout3.cfg +zc.buildout = 3.0.0b1
  buildout3.cfg +zc.recipe.egg = 2.0.7
host > MyComponent > Buildout > VirtualEnv('3') > VirtualEnvPy
host > MyComponent > Buildout > VirtualEnv('3') > Package('setuptools==54.1.1')
host > MyComponent > Buildout > VirtualEnv('3') > Package('wheel==0.36.2')
host > MyComponent > Buildout > VirtualEnv('3') > Package('zc.buildout==3.0.0b1')
host > MyComponent > Buildout
ERROR: bin/buildout -t 3 -c "buildout3.cfg"
Return code: 1
STDOUT
Setting socket time out to 3 seconds.
Creating directory '/tmp/pytest-of-jugmac00/pytest-0/test_runs_buildout3_successful0/work/mycomponent/eggs'.
Creating directory '/tmp/pytest-of-jugmac00/pytest-0/test_runs_buildout3_successful0/work/mycomponent/parts'.
Creating directory '/tmp/pytest-of-jugmac00/pytest-0/test_runs_buildout3_successful0/work/mycomponent/develop-eggs'.
Getting distribution for 'zc.recipe.egg==2.0.7'.
An error occurred when trying to install /tmp/tmp57kvb9qzget_dist/zc.recipe.egg-2.0.7.tar.gz. Look above this message for any errors that were output by pip install.

STDERR
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '_main' from 'pip.__main__' (/tmp/pytest-of-jugmac00/pytest-0/test_runs_buildout3_successful0/work/mycomponent/lib/python3.8/site-packages/pip/__main__.py)


___________________________________________________________ test_example_errors_early ____________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/tests/test_endtoend.py", line 21, in test_example_errors_early
    assert out == Ellipsis("""\
AssertionError: assert   batou/2.3b2.dev0 (cpython 3.10.0-beta1, Linux 5.4.0-73-generic x86_64)
    ================================== Preparing ===================================
    main: Loading environment `errors`...
    main: Verifying repository ...
    main: Loading secrets ...
    ERROR: Failed loading component file
          File: /home/jugmac00/Projects/batou/examples/errors/components/component5/component.py
  -  Exception: invalid syntax (component.py, line 1)...
  
  ...Full output truncated (16 lines hidden), use '-vv' to show
____________________________________________________________ test_example_errors_late ____________________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/tests/test_endtoend.py", line 56, in test_example_errors_late
    assert out == Ellipsis("""\
AssertionError: assert   batou/2.3b2.dev0 (cpython 3.10.0-beta1, Linux 5.4.0-73-generic x86_64)
    ================================== Preparing ===================================
    main: Loading environment `errors`...
    main: Verifying repository ...
    main: Loading secrets ...
    ================================ Connecting ... ================================
    localhost: Connecting via local (1/1)
    ============================ Configuring model ... =============================...
  
  ...Full output truncated (33 lines hidden), use '-vv' to show
______________________________________________________ test_remote_deployment_initializable ______________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/tests/test_remote.py", line 11, in test_remote_deployment_initializable
    cmd("hg init")
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 384, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
___________________________________________________ test_remote_bundle_breaks_on_missing_head ____________________________________________________
Traceback (most recent call last):
  File "/home/jugmac00/Projects/batou/src/batou/tests/test_remote.py", line 21, in test_remote_bundle_breaks_on_missing_head
    cmd("hg init")
  File "/home/jugmac00/Projects/batou/src/batou/utils.py", line 384, in cmd
    raise CmdExecutionError(cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: The deployment encountered an error.
------------------------------------------ generated xml file: /home/jugmac00/Projects/batou/report.xml ------------------------------------------

---------- coverage: platform linux, python 3.8.10-final-0 -----------
Coverage HTML written to dir htmlcov

============================================================ short test summary info =============================================================
FAILED src/batou/lib/tests/test_buildout.py::test_runs_buildout3_successfully - batou.utils.CmdExecutionError: The deployment encountered an er...
FAILED src/batou/tests/test_endtoend.py::test_example_errors_early - AssertionError: assert   batou/2.3b2.dev0 (cpython 3.10.0-beta1, Linux 5.4...
FAILED src/batou/tests/test_endtoend.py::test_example_errors_late - AssertionError: assert   batou/2.3b2.dev0 (cpython 3.10.0-beta1, Linux 5.4....
FAILED src/batou/tests/test_remote.py::test_remote_deployment_initializable - batou.utils.CmdExecutionError: The deployment encountered an error.
FAILED src/batou/tests/test_remote.py::test_remote_bundle_breaks_on_missing_head - batou.utils.CmdExecutionError: The deployment encountered an...
============================================== 5 failed, 345 passed, 2 skipped in 178.76s (0:02:58) ==============================================
ERROR: InvocationError for command /home/jugmac00/Projects/batou/.tox/skip-mercurial/bin/pytest --ignore=src/batou/lib/tests/test_mercurial.py src/batou (exited with code 1)
```

Ah, I see - even more mercurial related tests...

**Comment by jugmac00** [comment]
> This is a known bug in buildout 3 it appears:
> [buildout/buildout#567](https://github.com/buildout/buildout/issues/567)

https://xkcd.com/2347/ - though I think @gotcha is not from Nebraska :-)

**Comment by sallner** [comment]
As a workaround and a feature, we could add a `pip` attribute on the `Buildout` class, so that is possible to configure the pip version used. @ctheune would you vote for such a PR? I could make one, if you vote for it.

**Comment by ctheune** [comment]
Yeah, let's do this.
