### ISSUE TITLE
Compatibility problem with old 2.2.4 deployments while using 2.3b1 

### ISSUE THREAD

**Issue by nichmoe** [flyingcircusio/batou#182]
While updating some deployment it failed with the trace below. Batou 2.3b1 was used. The same problem did not occure with batou 2.2.4. A copy of of the repository where the problem occured can be found [here](https://yt.flyingcircus.io/issue/PL-129891).
```
Removing expired path: /Users/nichmoe/Repos/snipeit-batou/./.appenv/d0a893d8 ...
Creating venv ...
Ensuring pip ...
Installing ...
batou/2.3b1 (cpython 3.9.4-final0, Darwin 20.4.0 x86_64)
==== Preparing ====
main: Loading environment `vagrant`...
main: Verifying repository ...
You are using rsync. This is a non-verifying repository -- continuing on your own risk!
main: Loading secrets ...
==== Connecting ... ====
vagrant: Ensuring machines are up ...
default: Connecting via vagrant (1/1)
==== Configuring model ... ====
usage: batou [-h] [-d] {deploy,secrets} ...
batou: error: invalid choice: 'appenv-python' (choose from 'deploy', 'secrets')

ERROR: Unexpected exception
	Traceback (most recent call last):
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/host.py", line 191, in connect
    self.channel = self.gateway.remote_exec(remote_core)
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/execnet/gateway.py", line 130, in remote_exec
    channel = self.newchannel()
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/execnet/gateway_base.py", line 1015, in newchannel
    return self._channelfactory.new()
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/execnet/gateway_base.py", line 793, in new
    raise IOError("connexion already closed: {}".format(self.gateway))
	OSError: connexion already closed: <Gateway id='gw1' not-receiving, thread model, 0 active channels>
	During handling of the above exception, another exception occurred:
	Traceback (most recent call last):
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/deploy.py", line 227, in main
    getattr(deployment, step)()
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/deploy.py", line 99, in configure
    self.connections[0].join()
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/deploy.py", line 51, in join
    raise exc_value.with_traceback(exc_tb)
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/deploy.py", line 43, in run
    self.host.start()
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/host.py", line 216, in start
    self.connect(self.remote_base + "/batou appenv-python")
	File "/Users/nichmoe/Repos/snipeit-batou/.appenv/63103724/lib/python3.9/site-packages/batou/host.py", line 193, in connect
    raise RuntimeError(
	RuntimeError: Could not start batou on host `default`. The output above may contain more information.
==== DEPLOYMENT FAILED (during configure) ====

**Comment by ctheune** [comment]
This looks like the version of batou and appenv do not match.

**Comment by icemac** [comment]
This is currently only fixed on `master`, could we please have a 2.3b2 release?

**Comment by ctheune** [comment]
Sure. I'll cut a release later today, hopefully merging a few more PRs.

**Comment by ctheune** [comment]
Release is out now.
