### ISSUE TITLE
Deployment to remote host does not work.

### ISSUE THREAD

**Issue by sallner** [flyingcircusio/batou#188]
I was upgrading an already existing deployment from Batou 1 to 2.3b1 and got the following error:

```

/batou -d deploy staging
batou/2.3b1 (cpython 3.6.13-final0, Linux 5.12.8-arch1-1 x86_64)
===================================================== Preparing ======================================================
main: Loading environment `staging`...
main: Number of jobs: 1
main: Verifying repository ...
cmd: LANG=C LC_ALL=C LANGUAGE=C git status --porcelain
cmd: LANG=C LC_ALL=C LANGUAGE=C git log origin/staging..staging --pretty=oneline
main: Loading secrets ...
=================================================== Connecting ... ===================================================
XXX: Connecting via ssh (1/1)
Connecting ...
=============================================== Configuring model ... ================================================
Connected ...
XXX: Bootstrapping ...
rpc XXX: lock(*(), **{})
XXX: message: ('batou-result', 'OK')
rpc XXX: ensure_repository(*('~/deployment', 'git-bundle'), **{})
¹XXX: message: ('batou-result', '/srv/XXX/deployment')
rpc XXX: ensure_base(*('.',), **{})
XXX: message: ('batou-result', '/srv/XXX/deployment/.')
XXX: Updating repository ...
rpc XXX: git_current_head(*(), **{})
XXX: message: ('batou-result', b'1819dedf17069a44808776bb8f199d1d10b5d258')
cmd: LANG=C LC_ALL=C LANGUAGE=C git bundle create /tmp/tmp06b8q9ld 1819dedf17069a44808776bb8f199d1d10b5d258..staging
rpc XXX: git_update_working_copy(*('staging',), **{})
XXX: message: ('batou-result', '1819dedf17069a44808776bb8f199d1d10b5d258')
cmd: LANG=C LC_ALL=C LANGUAGE=C git rev-parse HEAD
rpc XXX: build_batou(*(), **{})
XXX: message: ('batou-result', None)
Disconnecting ...
Connecting ...
usage: batou [-h] [-d] {deploy,secrets} ...
batou: error: invalid choice: 'appenv-python' (choose from 'deploy', 'secrets')

ERROR: Unexpected exception
    Traceback (most recent call last):
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/host.py", line 191, in connect
    self.channel = self.gateway.remote_exec(remote_core)
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/execnet/gateway.py", line 131, in remote_exec
    channel = self.newchannel()
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/execnet/gateway_base.py", line 1015, in newchannel
    return self._channelfactory.new()
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/execnet/gateway_base.py", line 793, in new
    raise IOError("connexion already closed: {}".format(self.gateway))
    OSError: connexion already closed: <Gateway id='gw1' not-receiving, thread model, 0 active channels>
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/deploy.py", line 227, in main
    getattr(deployment, step)()
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/deploy.py", line 99, in configure
    self.connections[0].join()
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/deploy.py", line 51, in join
    raise exc_value.with_traceback(exc_tb)
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/deploy.py", line 43, in run
    self.host.start()
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/host.py", line 216, in start
    self.connect(self.remote_base + "/batou appenv-python")
    File "[...]/.appenv/3771e42e/lib/python3.6/site-packages/batou/host.py", line 196, in connect
    self.fqdn))
    RuntimeError: Could not start batou on host `XXX`. The output above may contain more information.

```

There seems to be a last residue from the rework of the appenv meta calls, which should be `"/appenv python"`
https://github.com/flyingcircusio/batou/blob/638038744281c804f2ad02c95c141f48b476b8fd/src/batou/host.py#L216

There is another place in the documentation that still mentions the old style. https://github.com/flyingcircusio/batou/blob/638038744281c804f2ad02c95c141f48b476b8fd/doc/source/upgrading.txt#L124

**Comment by ctheune** [comment]
Fix is underway, likely on the container branch. I'll merge the container branch soon.

**Comment by ctheune** [comment]
Fixed on the container branch which will be merged soon.
