### ISSUE TITLE
Why is "--ignore-installed" a default pip option?

### ISSUE THREAD

**Issue by sallner** [flyingcircusio/batou#212]
I tried to downgrade pip in a venv with Python 3.9 from 21.1.3 to 21.0.1 to be compatible with `zc.buildout`.
This broke pip as `locations.py` was moved from a module to being a package. With the option `"--ignore-installed"` enabled, this leads to the following broken import: 
```

python3.9 -m venv p39
p39/bin/pip install -U --ignore-installed pip==21.0.1
p39/bin/pip --help

```
```
 Traceback (most recent call last):
  File "[..]p39/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 14, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 29, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/locations/__init__.py", line 9, in <module>
    from . import _distutils, _sysconfig
  File "[..]p39/lib/python3.9/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' ([..]p39/lib/python3.9/site-packages/pip/_internal/exceptions.py)
```
The help information actually discourage the use of this option 

```
$ pip install --help

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

Description:
  Install packages from:
  
  - PyPI (and other indexes) using requirement specifiers.
  - VCS project urls.
  - Local project directories.
  - Local or remote source archives.
  
  pip also supports installing from "requirements files", which provide
  an easy way to specify a whole environment to be installed.

Install Options:

...

  -I, --ignore-installed      Ignore the installed packages, overwriting them. This can break your system if the existing package is of a different version or was installed with a different package manager!

...
```

So I was wondering about to reason to have this option since almost from the beginning of batou. 
The workaround is to fiddle with `install_options` from the sub_component in the adapted `configure()` of a custom `Buildout`-Component.

**Comment by ctheune** [comment]
From what I remember this was part of the initial effort to have things as replicatable as possible (similar to how buildout manages its dependencies). It looks like either this might have had a different meaning or did not have this warning back then.

Sounds like we should remove it then.
