### ISSUE TITLE
ConfigUpdater 3.1 results in error

### ISSUE THREAD

**Issue by schulztr** [flyingcircusio/batou#294]
By using the secrets subcommand with batou 2.3b2 the following traceback occurred during adding more than one member using `./batou secrets add <member>`. Using `ConfigUpdater` with Version `3.0.1` solved the problem. Any other commands concerning the secrets utility fail although. Although, a deployment doesn't work if more than one member is added.

```
Traceback (most recent call last):
  File "/..././.appenv/23dbf11a/bin/batou", line 33, in <module>
    sys.exit(load_entry_point('batou==2.3b2', 'console_scripts', 'batou')())
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/main.py", line 156, in main
    return args.func(**func_args)
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/manage.py", line 156, in add_user
    for e in Environment.by_filter(environments):
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/manage.py", line 57, in by_filter
    for e in cls.all():
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/manage.py", line 50, in all
    yield Environment(path=e)
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/manage.py", line 38, in __init__
    self.f.__enter__()
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/encryption.py", line 168, in __enter__
    self.read()
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/encryption.py", line 182, in read
    self.set_members(self.get_members())
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/batou/secrets/encryption.py", line 209, in set_members
    self.config.set("batou", "members", members)
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/configupdater/document.py", line 350, in set
    section_obj.set(option, value)
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/configupdater/section.py", line 271, in set
    self[option].value = value
  File "/.../.appenv/23dbf11a/lib/python3.10/site-packages/configupdater/option.py", line 181, in value
    raise AssignMultilineValueError(self)
configupdater.block.AssignMultilineValueError: Trying to assign a multi-line value to <Option 'members'>.
Use the ``set_values`` or ``append`` method to accomplish that.
```

**Comment by ctheune** [comment]
Thanks for the note. I fixed this in 5fb319f16429f7e36846a4e4411a1508458d8fa1 and we should finally be getting a new release out in the next days.
