### ISSUE TITLE
./batou deploy -c not working direct after migration to 2.3b4

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#319]
I've updated batou coming from 2.2.4 to 2.3.b4 and wanted to run a -c to check whether it's working

```
Connecting ...
-bash: line 1: /my/path/deployment/./appenv: No such file or directory
-bash: line 1: /my/path/deployment/./appenv: No such file or directory

ERROR: Unexpected exception
-bash: line 1: /my/path/deployment/./appenv: No such file or directory
	Traceback (most recent call last):
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/host.py", line 288, in connect
    self.channel = self.gateway.remote_exec(remote_core)
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/execnet/gateway.py", line 131, in remote_exec
    channel = self.newchannel()
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/execnet/gateway_base.py", line 1015, in newchannel
    return self._channelfactory.new()
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/execnet/gateway_base.py", line 793, in new
    raise IOError("connexion already closed: {}".format(self.gateway))
	OSError: connexion already closed: <Gateway id='gw6' not-receiving, thread model, 0 active channels>
	During handling of the above exception, another exception occurred:
	Traceback (most recent call last):
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/deploy.py", line 279, in main
    getattr(deployment, step)()
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/deploy.py", line 117, in configure
    self.connections[0].join()
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/deploy.py", line 49, in join
    raise exc_value.with_traceback(exc_tb)
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/deploy.py", line 41, in run
    self.host.start()
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/host.py", line 319, in start
    self.connect(self.remote_base + "/appenv python")
	File "/my/batou/repo/.appenv/a6d5a864/lib/python3.10/site-packages/batou/host.py", line 290, in connect
    raise RuntimeError(
	RuntimeError: Could not start batou on host `xxx.xxx.xxx`. The output above may contain more information.
==================================== CONSISTENCY CHECK FAILED (during configure) ====================================
-bash: line 1: /my/path/deployment/./appenv: No such file or directory
```

**Comment by ctheune** [comment]
This looks weird. This sounds like the #! interpreter in appenv is gone? Is this maybe related to your nixos store cleanup issues?

**Comment by ctheune** [comment]
Discussed with @frlan face to face and it was likely an on-vm userenv disaster and nothing directly batou related.
