### ISSUE TITLE
Test failures on master

### ISSUE THREAD

**Issue by icemac** [flyingcircusio/batou#37]
Running the tests of current master (aka 297349b) leads locally to 8 failures. CI tests did not run for the last couple of commits. Locally I get:

```
====================================================================================================== FAILURES ======================================================================================================
____________________________________________________________________________________________________ FLAKE8-check ____________________________________________________________________________________________________
/.../batou/src/batou/deploy.py:154:80: E501 line too long (80 > 79 characters)

____________________________________________________________________________________________________ FLAKE8-check ____________________________________________________________________________________________________
/.../batou/src/batou/main.py:128:8: E713 test for membership should be 'not in'

________________________________________________________________________________________________ test_downloads_file _________________________________________________________________________________________________
Traceback (most recent call last):
  File "/.../batou/src/batou/component.py", line 301, in deploy
    self.verify()
  File "/.../batou/src/batou/lib/download.py", line 33, in verify
    raise batou.UpdateNeeded()
batou.UpdateNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../batou/src/batou/lib/tests/test_download.py", line 53, in test_downloads_file
    root.component.deploy()
  File "/.../batou/src/batou/component.py", line 290, in deploy
    sub_component.deploy(predict_only)
  File "/.../batou/src/batou/component.py", line 312, in deploy
    self.update()
  File "/.../batou/src/batou/lib/download.py", line 41, in update
    self._update_requests()
  File "/.../batou/src/batou/lib/download.py", line 54, in _update_requests
    **(self.requests_kwargs if self.requests_kwargs else {}))
  File "/.../eggs/requests-2.22.0-py3.7.egg/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/.../eggs/requests-2.22.0-py3.7.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/.../eggs/requests-2.22.0-py3.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/.../eggs/requests-2.22.0-py3.7.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/.../eggs/requests-2.22.0-py3.7.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/.../eggs/urllib3-1.25.3-py3.7.egg/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/.../eggs/urllib3-1.25.3-py3.7.egg/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/.../eggs/urllib3-1.25.3-py3.7.egg/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/.../eggs/urllib3-1.25.3-py3.7.egg/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/.../eggs/urllib3-1.25.3-py3.7.egg/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
  File "/.../eggs/pytest_timeout-1.3.3-py3.7.egg/pytest_timeout.py", line 140, in handler
    timeout_sigalrm(item, params.timeout)
  File "/.../eggs/pytest_timeout-1.3.3-py3.7.egg/pytest_timeout.py", line 313, in timeout_sigalrm
    pytest.fail('Timeout >%ss' % timeout)
  File "/.../eggs/pytest-5.2.1-py3.7.egg/_pytest/outcomes.py", line 128, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >45.0s
_________________________________________________________________________________________ test_runs_svn_to_clone_repository __________________________________________________________________________________________
Traceback (most recent call last):
  File "/.../batou/src/batou/lib/tests/test_svn.py", line 10, in test_runs_svn_to_clone_repository
    cmd('svnadmin create ' + repos_path)
  File "/.../batou/src/batou/utils.py", line 344, in cmd
    cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: ('svnadmin create /private/var/folders/_2/5m3t4zvn29gb2f2_4phtk19r0000gn/T/pytest-of-mac/pytest-17/test_runs_svn_to_clone_reposit0/work/repos', 127, '', '/bin/sh: svnadmin: command not found\n')
________________________________________________________________________________________________ test_example_errors _________________________________________________________________________________________________
Traceback (most recent call last):
  File "/.../batou/src/batou/tests/test_endtoend.py", line 20, in test_example_errors
    assert out == Ellipsis("""\
AssertionError: assert - batou/2... (cpython 3...)
  +
  - ================================== Preparing ===================================
  - main: Loading environment `errors`...
  - main: Verifying repository ...
  - main: Loading secrets ...
  - ================================ Connecting ... ================================
  - localhost: Connecting via local (1/1)...

  ...Full output truncated (45 lines hidden), use '-vv' to show
______________________________________________________________________________________ test_example_errors_missing_environment _______________________________________________________________________________________
Traceback (most recent call last):
  File "/.../batou/src/batou/tests/test_endtoend.py", line 82, in test_example_errors_missing_environment
    assert out == Ellipsis("""\
AssertionError: assert - batou/2... (cpython 3...)
  +
  - ================================== Preparing ===================================
  - main: Loading environment `production`...
  - ERROR: Missing environment
  -      Environment: production
  - ============================== DEPLOYMENT FAILED ===============================
  -
________________________________________________________________________________________________ test_example_ignores ________________________________________________________________________________________________
Traceback (most recent call last):
  File "/.../batou/src/batou/tests/test_endtoend.py", line 96, in test_example_ignores
    out, _ = cmd('./batou deploy ignores')
  File "/.../batou/src/batou/utils.py", line 344, in cmd
    cmd, process.returncode, stdout, stderr)
batou.utils.CmdExecutionError: ('./batou deploy ignores', 1, '', 'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nModuleNotFoundError: No module named \'batou.bootstrap\'\n')
________________________________________________________________________________________ test_remote_deployment_initializable ________________________________________________________________________________________
Traceback (most recent call last):
  File "/.../batou/src/batou/tests/test_remote.py", line 17, in test_remote_deployment_initializable
    Deployment(env, platform='', timeout=30, fast=False, dirty=False)
TypeError: __init__() got an unexpected keyword argument 'fast'
------------------------------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------------------------------
Exception ignored in: <_io.FileIO name='/private/var/folders/_2/5m3t4zvn29gb2f2_4phtk19r0000gn/T/pytest-of-mac/pytest-17/test_remote_deployment_initial0/sample_service/components/hello/component.py' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/private/var/folders/_2/5m3t4zvn29gb2f2_4phtk19r0000gn/T/pytest-of-mac/pytest-17/test_remote_deployment_initial0/sample_service/components/hello/component.py' mode='r' encoding='UTF-8'>
----------------------------------------------------------------------------- generated xml file: /.../batou/report.xml -----------------------------------------------------------------------------

---------- coverage: platform darwin, python 3.7.7-final-0 -----------
Coverage HTML written to dir htmlcov

=============================================================================== 8 failed, 298 passed, 79 skipped in 177.15s (0:02:57) ================================================================================
```

**Comment by ctheune** [comment]
Tests worked for me now, Travis is still failing, for some reason ... sigh.

**Comment by icemac** [comment]
Master is green now on TravisCI. So closing this issue.
