### ISSUE TITLE
batou is currently not compatible with Python 3.9

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#93]
```
❯ ./batou deploy staging -P
Creating venv ...
Ensuring pip ...
Installing batou ...
batou/2.0 (cpython 3.9.0-candidate1, Linux 4.15.0-1096-oem x86_64)
===================================================================== Preparing =====================================================================
main: Loading environment `staging`...
main: Verifying repository ...
You are using rsync. This is a non-verifying repository -- continuing on your own risk!
main: Loading secrets ...
================================================================== Connecting ... ===================================================================
xxx.fcio.net: Connecting via ssh (1/4)
xxx.fcio.net: Connecting via ssh (2/4)
xxx.fcio.net: Connecting via ssh (3/4)
xxx.fcio.net: Connecting via ssh (4/4)
=============================================================== Configuring model ... ===============================================================
======================================================= Waiting for remaining connections ... =======================================================
=========================================================== Predicting deployment actions ===========================================================
ERROR: Unexpected exception
      Traceback (most recent call last):
        File "/home/jugmac00/Projects/bliss_deployment/.batou/a33c4220/lib/python3.9/site-packages/batou/deploy.py", line 200, in main
          deployment.deploy()
        File "/home/jugmac00/Projects/bliss_deployment/.batou/a33c4220/lib/python3.9/site-packages/batou/deploy.py", line 171, in deploy
          pending = asyncio.Task.all_tasks()
      AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
      
=========================================================== DEPLOYMENT PREDICTION FAILED ============================================================
```

From cpython source code
```
* The :meth:`asyncio.Task.current_task` and :meth:`asyncio.Task.all_tasks`
  have been removed. They were deprecated since Python 3.7 and you can use
  :func:`asyncio.current_task` and :func:`asyncio.all_tasks` instead.
  (Contributed by Rémi Lapeyre in :issue:`40967`)
```

My idea would be to use a switch and use either `asyncio.Task.all_tasks` or `asyncio.all_tasks` depending on the Python version.

PR will follow later this afternoon.

**Comment by zagy** [comment]
This is actually broken with 

      RuntimeError: no running event loop
